export const mockProducts = [
  {
    id: "1",
    name: "Camiseta Basic Preta",
    price: 89.9,
    oldPrice: 129.9,
    discount: 31,
    onSale: true,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
    colors: ["Preto", "Branco", "Cinza"],
    sizes: [
      { size: "P", stock: 10 },
      { size: "M", stock: 15 },
      { size: "G", stock: 8 },
      { size: "GG", stock: 5 },
    ],
    category: "basic",
  },
  {
    id: "2",
    name: "Camiseta Oversized Branca",
    price: 79.9,
    oldPrice: 99.9,
    discount: 20,
    onSale: true,
    image: "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=500",
    colors: ["Branco", "Bege", "Cinza Claro"],
    sizes: [
      { size: "P", stock: 12 },
      { size: "M", stock: 20 },
      { size: "G", stock: 15 },
      { size: "GG", stock: 10 },
    ],
    category: "oversized",
  },
  {
    id: "3",
    name: "Camiseta Estampada Urban",
    price: 99.9,
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500",
    colors: ["Preto", "Azul Marinho"],
    sizes: [
      { size: "P", stock: 5 },
      { size: "M", stock: 8 },
      { size: "G", stock: 12 },
      { size: "GG", stock: 7 },
    ],
    category: "estampada",
  },
  {
    id: "4",
    name: "Camiseta Polo Premium",
    price: 119.9,
    oldPrice: 159.9,
    discount: 25,
    onSale: true,
    image: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=500",
    colors: ["Azul Marinho", "Branco", "Preto", "Verde"],
    sizes: [
      { size: "P", stock: 8 },
      { size: "M", stock: 15 },
      { size: "G", stock: 10 },
      { size: "GG", stock: 6 },
    ],
    category: "polo",
  },
  {
    id: "5",
    name: "Camiseta Longline Cinza",
    price: 94.9,
    image: "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=500",
    colors: ["Cinza", "Preto", "Branco"],
    sizes: [
      { size: "P", stock: 10 },
      { size: "M", stock: 18 },
      { size: "G", stock: 12 },
      { size: "GG", stock: 8 },
    ],
    category: "longline",
  },
  {
    id: "6",
    name: "Camiseta Sport Dry Fit",
    price: 109.9,
    oldPrice: 149.9,
    discount: 27,
    onSale: true,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500",
    colors: ["Azul", "Preto", "Cinza", "Verde"],
    sizes: [
      { size: "P", stock: 15 },
      { size: "M", stock: 25 },
      { size: "G", stock: 20 },
      { size: "GG", stock: 12 },
    ],
    category: "sport",
  },
  {
    id: "7",
    name: "Camiseta Listrada Navy",
    price: 84.9,
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500",
    colors: ["Azul/Branco", "Preto/Branco"],
    sizes: [
      { size: "P", stock: 7 },
      { size: "M", stock: 12 },
      { size: "G", stock: 9 },
      { size: "GG", stock: 5 },
    ],
    category: "listrada",
  },
  {
    id: "8",
    name: "Camiseta Gola V Premium",
    price: 89.9,
    image: "https://images.unsplash.com/photo-1594938291221-94f18cbb5660?w=500",
    colors: ["Branco", "Preto", "Azul Marinho", "Cinza"],
    sizes: [
      { size: "P", stock: 10 },
      { size: "M", stock: 20 },
      { size: "G", stock: 15 },
      { size: "GG", stock: 10 },
    ],
    category: "basic",
  },
];

export const mockUsers = [
  {
    id: "1",
    email: "usuario@exemplo.com",
    password: "123456",
    name: "João Silva",
  },
];

export const mockOrders = [
  {
    id: "ORD-001",
    date: "2025-01-15",
    total: 269.7,
    status: "Entregue",
    items: [
      {
        productId: "1",
        name: "Camiseta Basic Preta",
        size: "M",
        color: "Preto",
        quantity: 2,
        price: 89.9,
      },
      {
        productId: "2",
        name: "Camiseta Oversized Branca",
        size: "G",
        color: "Branco",
        quantity: 1,
        price: 79.9,
      },
    ],
  },
  {
    id: "ORD-002",
    date: "2025-01-20",
    total: 219.8,
    status: "Em trânsito",
    items: [
      {
        productId: "4",
        name: "Camiseta Polo Premium",
        size: "M",
        color: "Azul Marinho",
        quantity: 1,
        price: 119.9,
      },
      {
        productId: "3",
        name: "Camiseta Estampada Urban",
        size: "G",
        color: "Preto",
        quantity: 1,
        price: 99.9,
      },
    ],
  },
];
